export const availableCodeLanguages = [
	{ name: 'Playwright', default: true, isDisabled: false },
	{ name: 'Selenium', default: false, isDisabled: true },
	{ name: 'Pupeeter', default: false, isDisabled: true },
];

export const availableCloudProviders = [
	{ name: 'AWS', default: true, isDisabled: false },
	{ name: 'Azure', default: false, isDisabled: true },
	{ name: 'Google Cloud', default: false, isDisabled: true },
];

export const availableTimeRange = [
	{ name: '1 minute', default: true, isDisabled: false },
	{ name: '2 minutes', default: false, isDisabled: false },
	{ name: '3 minutes', default: false, isDisabled: false },
	{ name: '5 minutes', default: false, isDisabled: false },
	{ name: '15 minutes', default: false, isDisabled: false },
	{ name: '60 minutes', default: false, isDisabled: false },
];
export const availableMethod = [
	{ name: 'Cloud' },
	{ name: 'Locally' }
]

export type rangeTimeVarEnvType = {
	[key: string]: number
}
export const rangeTimeVariable: rangeTimeVarEnvType =
{
	minute_1: 1,
	minutes_2: 2,
	minutes_3: 3,
	minutes_5: 5,
	minutes_15: 15,
	minutes_30: 30,
	minutes_60: 60
};

export const awsRegions = [
	{ name: 'us-east-2', default: true, isDisabled: false },
	{ name: 'us-east-1', default: false, isDisabled: false },
	{ name: 'us-west-1', default: false, isDisabled: false },
	{ name: 'us-west-2', default: false, isDisabled: false },
	{ name: 'ca-central-1', default: false, isDisabled: false },
	{ name: 'ap-southeast-3', default: false, isDisabled: false },
	{ name: 'ap-south-1', default: false, isDisabled: false },
	{ name: 'ap-south-2', default: false, isDisabled: false },
	{ name: 'ap-northeast-1', default: false, isDisabled: false },
	{ name: 'ap-northeast-2', default: false, isDisabled: false },
	{ name: 'ap-northeast-3', default: false, isDisabled: false },
	{ name: 'ap-southeast-1', default: false, isDisabled: false },
	{ name: 'ap-southeast-2', default: false, isDisabled: false },
	{ name: 'eu-central-1', default: false, isDisabled: false },
	{ name: 'eu-central-2', default: false, isDisabled: false },
	{ name: 'eu-north-1', default: false, isDisabled: false },
	{ name: 'me-south-1', default: false, isDisabled: false },
	{ name: 'me-central-1', default: false, isDisabled: false },
	{ name: 'eu-west-1', default: false, isDisabled: false },
	{ name: 'eu-west-2', default: false, isDisabled: false },
	{ name: 'eu-west-3', default: false, isDisabled: false },
	{ name: 'eu-south-1', default: false, isDisabled: false },
	{ name: 'eu-south-2', default: false, isDisabled: false },
	{ name: 'sa-east-1', default: false, isDisabled: false },
	{ name: 'cn-north-1', default: false, isDisabled: false },
	{ name: 'cn-northwest-1', default: false, isDisabled: false },
	{ name: 'ap-east-1', default: false, isDisabled: false },
	{ name: 'af-south-1', default: false, isDisabled: false },
	{ name: 'us-gov-west-1', default: false, isDisabled: false },
	{ name: 'us-gov-east-1', default: false, isDisabled: false },
]

export const platformDevice = [
	{ name: 'Desktop Chrome', default: true, isDisabled: false },
	{ name: 'Blackberry PlayBook', default: false, isDisabled: false },
	{ name: 'Blackberry PlayBook landscape', default: false, isDisabled: false },
	{ name: 'BlackBerry Z30', default: false, isDisabled: false },
	{ name: 'BlackBerry Z30 landscape', default: false, isDisabled: false },
	{ name: 'Galaxy Note 3', default: false, isDisabled: false },
	{ name: 'Galaxy Note 3 landscape', default: false, isDisabled: false },
	{ name: 'Galaxy Note II', default: false, isDisabled: false },
	{ name: 'Galaxy Note II landscape', default: false, isDisabled: false },
	{ name: 'Galaxy S III', default: false, isDisabled: false },
	{ name: 'Galaxy S III landscape', default: false, isDisabled: false },
	{ name: 'Galaxy S5', default: false, isDisabled: false },
	{ name: 'Galaxy S5 landscape', default: false, isDisabled: false },
	{ name: 'Galaxy S8', default: false, isDisabled: false },
	{ name: 'Galaxy S8 landscape', default: false, isDisabled: false },
	{ name: 'Galaxy S9+', default: false, isDisabled: false },
	{ name: 'Galaxy S9+ landscape', default: false, isDisabled: false },
	{ name: 'Galaxy Tab S4', default: false, isDisabled: false },
	{ name: 'Galaxy Tab S4 landscape', default: false, isDisabled: false },
	{ name: 'iPad (gen 6)', default: false, isDisabled: false },
	{ name: 'iPad (gen 6) landscape', default: false, isDisabled: false },
	{ name: 'iPad (gen 7)', default: false, isDisabled: false },
	{ name: 'iPad (gen 7) landscape', default: false, isDisabled: false },
	{ name: 'iPad Mini', default: false, isDisabled: false },
	{ name: 'iPad Mini landscape', default: false, isDisabled: false },
	{ name: 'iPad Pro 11', default: false, isDisabled: false },
	{ name: 'iPad Pro 11 landscape', default: false, isDisabled: false },
	{ name: 'iPhone 6', default: false, isDisabled: false },
	{ name: 'iPhone 6 landscape', default: false, isDisabled: false },
	{ name: 'iPhone 6 Plus', default: false, isDisabled: false },
	{ name: 'iPhone 6 Plus landscape', default: false, isDisabled: false },
	{ name: 'iPhone 7', default: false, isDisabled: false },
	{ name: 'iPhone 7 landscape', default: false, isDisabled: false },
	{ name: 'iPhone 7 Plus', default: false, isDisabled: false },
	{ name: 'iPhone 7 Plus landscape', default: false, isDisabled: false },
	{ name: 'iPhone 8', default: false, isDisabled: false },
	{ name: 'iPhone 8 landscape', default: false, isDisabled: false },
	{ name: 'iPhone 8 Plus', default: false, isDisabled: false },
	{ name: 'iPhone 8 Plus landscape', default: false, isDisabled: false },
	{ name: 'iPhone SE', default: false, isDisabled: false },
	{ name: 'iPhone SE landscape', default: false, isDisabled: false },
	{ name: 'iPhone X', default: false, isDisabled: false },
	{ name: 'iPhone X landscape', default: false, isDisabled: false },
	{ name: 'iPhone XR', default: false, isDisabled: false },
	{ name: 'iPhone XR landscape', default: false, isDisabled: false },
	{ name: 'iPhone 11', default: false, isDisabled: false },
	{ name: 'iPhone 11 landscape', default: false, isDisabled: false },
	{ name: 'iPhone 11 Pro', default: false, isDisabled: false },
	{ name: 'iPhone 11 Pro landscape', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
	{ name: '', default: false, isDisabled: false },
]